### ISSUE TITLE
Low FPS

### ISSUE THREAD

**Issue by rhyzx** [MassiveHeights/Black-Donuts#2]
Hello, I found the fps is low when trying this example, about 40 ~ 50fps (Macbook Pro 2015, Chrome), I think for a 2d game, this is not reasonable, can you give some optimization suggestions?

**Comment by 62316e** [comment]
Can you please confirm you are using GCC build "npm run bundle"?

**Comment by rhyzx** [comment]
![image](https://user-images.githubusercontent.com/1676871/46052476-2f126500-c171-11e8-9e6a-2d23d41b6863.png)

I ran it the way as `npm run bundle && http-server dist`, and the results were about the same. Besides, I tested it on my colleague's computer(Macbook Pro 2013 13inch) and it turned out to be even worse, only about 10 fps.

**Comment by 62316e** [comment]
Hi @rhyzx 
We ran a few tests with High DPR enabled and disabled.

I can confirm that FPS is two times lower on MacBook Pro with High DPR enabled.
The funny fact is that tests on Android and iOS showed the same results.

The `resolution` property will be added to CanvasDriver in the next release.

**Comment by rhyzx** [comment]
I see, thanks @62316e . So is this the performance limit for canvas? Is it only possible to switch to WEBGL to achieve higher performance for this game? I was wondering if there was any space for canvas to optimize.

**Comment by 62316e** [comment]
New ‘resolution’ property will fix poor performance on macbooks in this case.

WebGL will be faster for sure. (Coming soon)

The reason why we picked canvas is old device support and it works more stable then WebGL.

Also fallback to canvas is must have option when developing for Facebook Instant Games Lightweight.

There is no “universal solution” atm. You have to pick between target audiance/quality/performance.

**Comment by rhyzx** [comment]
Got it. Thank you.

**Comment by 62316e** [comment]
Please take a look into `0.6.x-dev` branch. Added `UseHiDPR` property.
FPS should be ok for you now.
