### ISSUE TITLE
Game Scaling and Grid

### ISSUE THREAD

**Issue by wini3d** [MassiveHeights/Black-Donuts#5]
Hi, It seems the example is different from the online demo [here](https://blacksmith2d.io/content/shared/black-donuts/). I'm getting a scaled up version and if I try to set the size the grid never ends. 

So how do I set it up and control the grid same as the online demo which is a 7x5 grid?

**Comment by 62316e** [comment]
Please take a look into `board.js` and look for:
```
    this.gridWidth = w;
    this.gridHeight = h;
```

Feel free to use [Discord](https://discord.gg/HWzzCcy) for those types of questions.
